### ISSUE TITLE
Unable to install mass library 

### ISSUE THREAD

**Issue by Gautham16-g** [Pradip-p/E-Health-Care#29]
root ➜ /com.docker.devenvironments.code (master ✗) $ python manage.py runserver
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python3.9/dist-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 398, in execute
    autoreload.check_errors(django.setup)()
  File "/usr/local/lib/python3.9/dist-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/dist-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/com.docker.devenvironments.code/doctor/apps.py", line 8, in ready
    import social.mysignal
  File "/usr/local/lib/python3.9/dist-packages/social/__init__.py", line 5, in <module>
    from .fsong import *
  File "/usr/local/lib/python3.9/dist-packages/social/fsong.py", line 1, in <module>
    import gmane as g, networkx as x, pylab as p, numpy as n, os
  File "/usr/local/lib/python3.9/dist-packages/gmane/__init__.py", line 32, in <module>
    from .evolutionMusic import EvolutionMusic
  File "/usr/local/lib/python3.9/dist-packages/gmane/evolutionMusic.py", line 1, in <module>
    import mass as m, numpy as n, os, pickle
ModuleNotFoundError: No module named 'mass'

**Comment by Gautham16-g** [comment]
Collecting mass
  Using cached mass-0.1.3.tar.gz (4.9 kB)
  Using cached mass-0.1.2.tar.gz (4.9 kB)
  Using cached mass-0.1.1.tar.gz (4.8 kB)
  Using cached mass-0.1.0.tar.gz (3.0 kB)
ERROR: Cannot install mass==0.1.0, mass==0.1.1, mass==0.1.2, mass==0.1.3 and mass==0.1.4 because these package versions have conflicting dependencies.

The conflict is caused by:
    mass 0.1.4 depends on distribute
    mass 0.1.3 depends on distribute
    mass 0.1.2 depends on distribute
    mass 0.1.1 depends on distribute
    mass 0.1.0 depends on distribute

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

**Comment by Pradip-p** [comment]
I suggest reaching out to the project maintainer to check if they have updated the requirements.txt file recently. You can also try searching for updated dependencies and updating the requirements.txt file yourself.

Once you have the updated requirements.txt file, you can try running the application again. Hopefully, this will resolve the issue you are facing.
